CREATE TABLE IF NOT EXISTS usuarios (
	id uuid UNIQUE PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	barco TEXT NOT NULL DEFAULT 'default',
	tablero TEXT NOT NULL DEFAULT 'default',
	elo INTEGER NOT NULL DEFAULT 1000,
	partidas_jugadas INTEGER NOT NULL CHECK (partidas_jugadas >= 0) DEFAULT 0,
	partidas_ganadas INTEGER NOT NULL CHECK (partidas_ganadas >= 0) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS partidas (
	id TEXT PRIMARY KEY NOT NULL,
	estado JSONB,
	jugador1_id TEXT NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
	jugador2_id TEXT NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
	ranked BOOLEAN NOT NULL DEFAULT FALSE,
	fecha_ultimo_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	activa BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS historial_partidas (
	id TEXT PRIMARY KEY NOT NULL,
	jugador1_id TEXT NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
	jugador2_id TEXT NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
	ranked BOOLEAN NOT NULL DEFAULT FALSE,
	ganador_id TEXT NOT NULL REFERENCES usuarios(username) ON DELETE CASCADE,
	fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);